version: 0.0
os: linux
files:
  - source: /target/demo-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
