version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Building the application...
      - mvn clean package
artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
