version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo Building the application...
      - mvn clean package
artifacts:
  files:
    - ./**/**
